version: '2'

services:
  web:
    build: web/.
    image: thekevjames/thekev.in
    environment:
      - DROPBOX_TOKEN=${DROPBOX_TOKEN}
      - SENTRY_DSN=${SENTRY_DSN_THEKEVIN}
    ports:
      - "28005:5000"
