version: 2

jobs:
  check:
    docker:
      # https://github.com/docker-library/python/issues/155
      # - image: python:3.6.2-alpine3.6
      - image: python:3.6.2
    steps:
      - checkout
      - run: pip install pre-commit
      - run: pre-commit run --all-files

  thekevin:
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - setup_remote_docker:
          version: 17.05.0-ce
      - run: docker version
      - run:
          name: build image
          command: |
            docker build -t web .
            docker tag web "thekevjames/thekev.in:${CIRCLE_SHA1}"
            docker tag web "thekevjames/thekev.in:latest"
      - deploy:
          name: push image
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              docker login -u ${DOCKER_USER} -p ${DOCKER_PASS}

              docker push "thekevjames/thekev.in:${CIRCLE_SHA1}"
              docker push "thekevjames/thekev.in:latest"
            fi

  deploy:
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - deploy:
          name: deploy image
          command: |
            ssh -oStrictHostKeyChecking=no ubuntu@thekev.in "
              docker service update --image thekevjames/thekev.in:${CIRCLE_SHA1} thekevjames_thekevin
            "

workflows:
  version: 2
  check-build-and-deploy:
    jobs:
      - check

      - thekevin:
          context: org-global
          requires:
            - check

      - deploy:
          requires:
            - thekevin
          filters:
            branches:
              only: master
